openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /execute:
    post:
      operationId: postExecute
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecuteCommandInput'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    ExecuteCommandInput:
      required:
      - command
      type: object
      properties:
        command:
          type: string
